FROM openjdk:jre
ADD https://github.com/dokterbob/ipfs-tika/releases/download/v0.3.1/ipfs-tika-0.3.1-jar-with-dependencies.jar .
EXPOSE 8081
CMD ["java", "-jar", "/ipfs-tika-0.3.1-jar-with-dependencies.jar"]
