---
- name: Assure we have a containing folder with permission to clone in
  file: path="{{ frontend_install_path }}/.." state=directory owner="{{ lookup('env','USER') }}"
- block:
  - name: Clone frontend
    git:
      repo: https://github.com/ipfs-search/ipfs-search-frontend.git
      dest: "{{ frontend_install_path }}"
      version: v2
    register: git
  - block:
    - name: Install frontend dependencies
      command: npm install
      args:
        chdir: "{{ frontend_install_path }}"
    - name: Build frontend
      shell: "$(npm bin)/ember build --environment production"
      args:
        chdir: "{{ frontend_install_path }}"
    when: git.changed
  become: false
- name: Install nginx configuration
  template: src=nginx-frontend.conf dest=/etc/nginx/sites-available/frontend.conf
  notify: restart nginx
- name: Enable nginx configuration
  file:
    path: /etc/nginx/sites-enabled/frontend.conf
    src: /etc/nginx/sites-available/frontend.conf
    state: link
  notify: restart nginx
