ipfs:
    api_url: http://localhost:5001
    gateway_url: http://localhost:8080
    partial_size: 256KB
opensearch:
    url: http://localhost:9200
    bulk_indexer_workers: 8
    bulk_flush_bytes: 5000000B
    bulk_getter_batch_size: 48
    bulk_getter_batch_timeout: 150ms
redis:
    addresses:
        - localhost:6379
amqp:
    url: amqp://guest:guest@localhost:5672/
    max_reconnect: 100
    reconnect_time: 2s
    message_ttl: 4h
tika:
    url: http://localhost:8081
    timeout: 5m
    max_file_size: 4GB
nsfw:
    url: http://localhost:3000
    timeout: 5m
    max_file_size: 1GB
instrumentation:
    sampling_ratio: 0.01
    jaeger_endpoint: http://localhost:14268/api/traces
crawler:
    direntry_buffer_size: 8192
    min_update_age: 1h
    stat_timeout: 1m
    direntry_timeout: 1m
    max_dirsize: 32768
sniffer:
    lastseen_expiration: 1h
    lastseen_prunelen: 32768
    logger_timeout: 1m
    buffer_size: 512
indexes:
    files:
        name: ipfs_files
        prefix: f
    directories:
        name: ipfs_directories
        prefix: d
    invalids:
        name: ipfs_invalids
        prefix: i
    partials:
        name: ipfs_partials
        prefix: p
queues:
    files:
        name: files
    directories:
        name: directories
    hashes:
        name: hashes
workers:
    hash_workers: 70
    file_workers: 120
    directory_workers: 70
    ipfs_max_connections: 1000
    extractor_max_connections: 100
    throttle_max_load: 0.7
    throttle_min_wait: 2s
    throttle_max_wait: 1m
